version: "3"
services:
  backend_user:
    image: marco5/udagram-api_users
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME : $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
      POSTGRES_DB: $POSTGRES_DB 
      POSTGRES_HOST: $POSTGRES_HOST 
      AWS_REGION: $AWS_REGION 
      AWS_PROFILE: $AWS_PROFILE 
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
  backend_feed:
    image: marco5/udagram-api_feed
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME : $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
      POSTGRES_DB: $POSTGRES_DB 
      POSTGRES_HOST: $POSTGRES_HOST 
      AWS_REGION: $AWS_REGION 
      AWS_PROFILE: $AWS_PROFILE 
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
  reverseproxy:
      image: marco5/reverse-proxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend_user
        - backend_feed     
  udagram-frontend:
    image: marco5/udagram-frontend
    ports:
      - "8100:80"